### PR TITLE
feat: add uglify plugin

### PR DESCRIPTION
**Pull request by yugasun**
For `umd` output, i think mostly we use it in browser, so this file should be compressed, so I add [rollup-plugin-uglify](https://github.com/TrySound/rollup-plugin-uglify) for this job, but `rollup@0.57.1` is incompatible with `rollup-plugin-uglify@6.0.0` (the lasted version), so I updated `rollup` version too.

### CODE REVIEW

**Comment by yugasun** [comment]
Travis CI faliled on `nodejs@4`, I think we can get rid of this version. What do you think?

**Comment by yanhaijing** [comment]
>For umd output, i think mostly we use it in browser, so this file should be compressed

I think so

**Comment by yanhaijing** [comment]
> but rollup@0.57.1 is incompatible with rollup-plugin-uglify@6.0.0 (the lasted version), so I updated rollup version too

no problem，but new version compatible is .?

**Comment by yanhaijing** [comment]
I think aio file should provide `xxx.aio.js` and `xxx.aio.min.js`

**Comment by yanhaijing** [comment]
Plus you're interested in joining @jsmini ?
https://github.com/jsmini

**Comment by yugasun** [comment]
> Plus you're interested in joining @jsmini ?
> https://github.com/jsmini

My  pleasure.

**Comment by yugasun** [comment]
> Plus you're interested in joining @jsmini ?
> https://github.com/jsmini

My  pleasure.

**Comment by yugasun** [comment]
> > but rollup@0.57.1 is incompatible with rollup-plugin-uglify@6.0.0 (the lasted version), so I updated rollup version too
> 
> no problem，but new version compatible is .?

`rollup@0.57.1` is compatible with `rollup-plugin-uglify@4.0.0`, so I update this pr again with `rollup@0.57.1` and `rollup-plugin-uglify@4.0.0`.

**Comment by yugasun** [comment]
Because I do some wrong handles, I have to close this pr.

**Comment by yanhaijing** [comment]
@yugasun 那麻烦加一下微信 yanhaijing123，O(∩_∩)O哈哈~

**Pull request closed without merging**
